[versions]
jvmTarget = "21"
kotlin = "2.0.0"
doodle = "0.9.0"
javafx = "21"

[libraries]

[bundles]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

javafx = "org.openjfx.javafxplugin:0.1.0"

spotless = "com.diffplug.spotless:6.25.0"
