[versions]
jvmTarget = "17"
kotlin = "1.8.0"
doodle = "0.9.0"
javafx = "17"

[libraries]

[bundles]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

javafx = "org.openjfx.javafxplugin:0.0.13"

spotless = "com.diffplug.spotless:6.15.0"
